### ISSUE TITLE
报错？

### ISSUE THREAD

**Issue by Jaie0801** [timwhitez/Frog-Auth#4]
Ports Scanning.
[FTL] Could not create runner: Get "https://www.cloudflare.com/ips-v4": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Command '['./ports/naabu_win.exe', '-iL', '.\\ip.txt', '-p', '21,80,81,443,616,873,990,993,2181,2375,2376,2600,3000,3001,3306,3307,3310,3311,3312,3333,4040,4443,5000,5001,5060,5601,5984,5986,6006,6060,6066,6379,6699,6779,6969,7000,7001,7002,7402,7777,8000,8001,8010,8020,8025,8030,8042,8080,8081,8082,8083,8085,8086,8088,8089,8090,8099,8181,8443,8480,8886,8888,8983,9000,9002,9003,9080,9090,9200,9300,9443,9527,9870,9999,10000,11211,15000,15001,15002,18081,20000,27017,27018,28017,32768,50000,50030,50070,50075,50090,21502', '-nC', '-privileged', '-silent', '-ping', 'false', '-rate', '1000', '-no-probe']' returned non-zero exit status 1.
爆出这种信息是发生了什么吗

**Comment by timwhitez** [comment]
扫描端口的时候，naabu会去请求https://www.cloudflare.com/ips-v4
以去除cdn段，这个报错就是请求失败

**Comment by timwhitez** [comment]
后续我看看怎么解决这个问题吧

**Comment by whoimi199** [comment]
执行报这个问题，是不是代码路径有问题啊。
![图片](https://user-images.githubusercontent.com/58024023/126422759-3604ad6f-44f1-40cc-b293-ef727fdd0d5e.png)

**Comment by whoimi199** [comment]
解决了大佬，我把naabu更新了一下，然后不不支持的命令替换了。

**Comment by whoimi199** [comment]
许个愿，可以增加一个扫描过程，进度条那种展示吗？感觉这样友好一点。

**Comment by timwhitez** [comment]
我老鸽子了,hhhh等有空了我看看
大佬们也可以多提pr

**Comment by timwhitez** [comment]
> 解决了大佬，我把naabu更新了一下，然后不不支持的命令替换了。

更新后的命令可以提一下pr，我合并分支
